/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EmployeeTaskSystem;

import java.util.List;

import org.springframework.context.support-3.1.0.RELEASE.jar;
import java.util.List;


public class Library {
    public boolean someLibraryMethod() 
    {
        return true;
    }
    
    public static void main(String [] args)
    {
    	ApplicationContext context = new ClassPathXmlApplicationContext("springbean.xml");
    	
    	Employee E = context.getBean("employee",Employee.class);
    	System.out.println("Employee 1 details:")
    	System.out.println("Employee id = " + E.getEmployeeid());
    	System.out.println("Employee name = " + E.getEmployee_name());
    	System.out.println("Employee department = " + E.getDepartment());
    	System.out.println("Employee designation = " + E.getDesignation());
    	System.out.println("Employee password = " + E.getPassword());
	
    	Task T = context.getBean("task1", Task.class);
    	List<Task> task = T.getTasklist();
    	for(Task t : task)
    	{
    		System.out.println("Task id = " + t.getTaskid());
    		System.out.println("Task name = " + t.getTaskname());
    		System.out.println("Task description = " + t.getTask_description());
    		System.out.println("Date of Allocation = " + t.getDate_of_allocation());
    		System.out.println("Deadline = " + t.getDeadline());
    		System.out.println("Allocated to = " + t.getAllocated_to());
    		
    	}
    	Task T1 = context.getBean("task2", Task.class)
    	List<Task> task1 = T1.getTasklist();
    	for(Task t : task1)
    	{
    		System.out.println("Task id = " + t.getTaskid());
    	    System.out.println("Task name = " + t.getTaskname());
    	    System.out.println("Task description = " + t.getTask_description());
    	    System.out.println("Date of Allocation = " + t.getDate_of_allocation());
    	    System.out.println("Deadline = " + t.getDeadline());
    	    System.out.println("Allocated to = " + t.getAllocated_to());  		
    	}
    	Attendance A = context.getBean("day1", Attendance.class);
    	List<Attendance> att = A.getAttendance_list();
    	for(Attendance a : att)
    	{
    		System.out.println("Attendance id = " + a.getAttendance_id());
    		System.out.println("Attendande date = " + a.getAttendance_date());
    		System.out.println("Attendance Status = " + a.getStatus());
    	}
  
    	Attendance A22 = context.getBean("day2", Attendance.class);
    	List<Attendance> att22 = A22.getAttendance_list();
    	for(Attendance a : att)
    	{
    		System.out.println("Attendance id = " + a.getAttendance_id());
    		System.out.println("Attendande date = " + a.getAttendance_date());
    		System.out.println("Attendance Status = " + a.getStatus());
    	}

    	Attendance A11 = context.getBean("day3", Attendance.class);
    	List<Attendance> att11 = A11.getAttendance_list();
    	for(Attendance a : att11)
    	{
    		System.out.println("Attendance id = " + a.getAttendance_id());
    		System.out.println("Attendande date = " + a.getAttendance_date());
    		System.out.println("Attendance Status = " + a.getStatus());
    	}
    	Attendance A2 = context.getBean("day4", Attendance.class);
    	List<Attendance> att2 = A2.getAttendance_list();
    	for(Attendance a : att2)
    	{
    		System.out.println("Attendance id = " + a.getAttendance_id());
    		System.out.println("Attendande date = " + a.getAttendance_date());
    		System.out.println("Attendance Status = " + a.getStatus());
    	}
    	
    	System.out.println("Employee Rating = " + E.getEmployee_rating());
    	
//================================================================================================
    	
    	Employee E1 = context.getBean("employee2",Employee.class);
    	System.out.println("Employee 2 details:");
    	System.out.println("Employee id = " + E1.getEmployeeid());
    	System.out.println("Employee name = " + E1.getEmployee_name());
    	System.out.println("Employee department = " + E1.getDepartment());
    	System.out.println("Employee designation = " + E1.getDesignation());
    	System.out.println("Employee password = " + E1.getPassword());
	
    	Task TT = context.getBean("task1", Task.class);
    	List<Task> tt1 = TT.getTasklist();
    	for(Task t : tt1)
    	{
    		System.out.println("Task id = " + t.getTaskid());
    		System.out.println("Task name = " + t.getTaskname());
    		System.out.println("Task description = " + t.getTask_description());
    		System.out.println("Date of Allocation = " + t.getDate_of_allocation());
    		System.out.println("Deadline = " + t.getDeadline());
    		System.out.println("Allocated to = " + t.getAllocated_to());
    		
    	}
    	Task TT1 = context.getBean("task2", Task.class);
    	List<Task> ta1 = TT1.getTasklist();
    	for(Task t : task1)
    	{
    		System.out.println("Task id = " + t.getTaskid());
    	    System.out.println("Task name = " + t.getTaskname());
    	    System.out.println("Task description = " + t.getTask_description());
    	    System.out.println("Date of Allocation = " + t.getDate_of_allocation());
    	    System.out.println("Deadline = " + t.getDeadline());
    	    System.out.println("Allocated to = " + t.getAllocated_to());  		
    	}
    	Task TT11 = context.getBean("task2", Task.class);
    	List<Task> ta11 = TT11.getTasklist();
    	for(Task t : task1)
    	{
    		System.out.println("Task id = " + t.getTaskid());
    	    System.out.println("Task name = " + t.getTaskname());
    	    System.out.println("Task description = " + t.getTask_description());
    	    System.out.println("Date of Allocation = " + t.getDate_of_allocation());
    	    System.out.println("Deadline = " + t.getDeadline());
    	    System.out.println("Allocated to = " + t.getAllocated_to());  		
    	}
    	
    	Attendance S = context.getBean("day1", Attendance.class);
    	List<Attendance> s = S.getAttendance_list();
    	for(Attendance a : s)
    	{
    		System.out.println("Attendance id = " + a.getAttendance_id());
    		System.out.println("Attendande date = " + a.getAttendance_date());
    		System.out.println("Attendance Status = " + a.getStatus());
    	}
    	Attendance K = context.getBean("day2", Attendance.class);
    	List<Attendance> k = K.getAttendance_list();
    	for(Attendance a : att)
    	{
    		System.out.println("Attendance id = " + a.getAttendance_id());
    		System.out.println("Attendande date = " + a.getAttendance_date());
    		System.out.println("Attendance Status = " + a.getStatus());
    	}Attendance H = context.getBean("day1", Attendance.class);
    	List<Attendance> h = H.getAttendance_list();
    	for(Attendance a : h)
    	{
    		System.out.println("Attendance id = " + a.getAttendance_id());
    		System.out.println("Attendande date = " + a.getAttendance_date());
    		System.out.println("Attendance Status = " + a.getStatus());
    	}
    	Attendance I = context.getBean("day3", Attendance.class);
    	List<Attendance> i = EI.getAttendance_list();
    	for(Attendance a : i)
    	{
    		System.out.println("Attendance id = " + a.getAttendance_id());
    		System.out.println("Attendande date = " + a.getAttendance_date());
    		System.out.println("Attendance Status = " + a.getStatus());
    	}
    	System.out.println("Employee Rating = " + E1.getEmployee_rating());
    	
    }
}
